import { useEffect,useMemo,useState } from "react";
import { getDashboardAnalytics,exportDashboardAnalytics } from "../services/dashboard.service";
import { getPrograms } from "../../../services/program.service";
import { getBatches } from "../../../services/batch.service";
import { getDistricts } from "../../../services/district.service";
import { getBlocks } from "../../../services/block.service";
import { getCenters } from "../../../services/center.service";

const date=(d)=>new Date(d).toISOString().slice(0,10); const today=date(new Date()); const past=date(new Date(Date.now()-29*86400000));
const Card=({title,value,sub})=><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{title}</p><p className="mt-2 text-3xl font-black text-slate-900">{value}</p>{sub&&<p className="mt-1 text-xs text-slate-500">{sub}</p>}</div>;
export default function DashboardAnalytics(){const [filters,setFilters]=useState({from:past,to:today,programId:"",batchId:"",districtId:"",blockId:"",centerId:""});const [d,setD]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");const [lists,setLists]=useState({programs:[],batches:[],districts:[],blocks:[],centers:[]});
 const load=async()=>{try{setLoading(true);const r=await getDashboardAnalytics(Object.fromEntries(Object.entries(filters).filter(([,v])=>v)));setD(r.data)}catch(e){setError(e.response?.data?.message||"Unable to load analytics")}finally{setLoading(false)}};
 useEffect(()=>{Promise.all([getPrograms({page:1,limit:100}),getBatches({page:1,limit:200}),getDistricts({page:1,limit:100}),getBlocks({page:1,limit:300}),getCenters({page:1,limit:500})]).then(([p,b,d,bl,c])=>setLists({programs:p.data?.programs||[],batches:b.data?.batches||[],districts:d.data?.districts||[],blocks:bl.data?.blocks||[],centers:c.data?.centers||[]})).catch(()=>{});load()},[]);
 const set=(k,v)=>setFilters(x=>({...x,[k]:v})); const exportIt=async(format)=>{const blob=await exportDashboardAnalytics({...filters,format});const u=URL.createObjectURL(blob);const a=document.createElement("a");a.href=u;a.download=`dashboard-${filters.from}-${filters.to}.${format}`;a.click();URL.revokeObjectURL(u)};
 const filteredB=useMemo(()=>lists.batches.filter(x=>!filters.programId||String(x.programId?._id||x.programId)===filters.programId),[lists.batches,filters.programId]); const filteredBl=useMemo(()=>lists.blocks.filter(x=>!filters.districtId||String(x.districtId?._id||x.districtId)===filters.districtId),[lists.blocks,filters.districtId]); const filteredC=useMemo(()=>lists.centers.filter(x=>(!filters.districtId||String(x.districtId?._id||x.districtId)===filters.districtId)&&(!filters.blockId||String(x.blockId?._id||x.blockId)===filters.blockId)),[lists.centers,filters.districtId,filters.blockId]);
 return <div className="min-h-full bg-slate-50 p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl space-y-6"><section className="rounded-3xl bg-gradient-to-br from-slate-950 via-indigo-950 to-indigo-800 p-7 text-white shadow-xl"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-indigo-200">ERP Intelligence</p><h1 className="mt-2 text-3xl font-black">Student & Operations Analytics</h1><p className="mt-2 text-sm text-indigo-100/80">Attendance, absentee calling, exams, marks, center PDFs and student performance — restricted to your program, batch and region access.</p></div><div className="flex gap-2"><button onClick={()=>exportIt("xlsx")} className="rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-slate-900">Export Excel</button><button onClick={()=>exportIt("csv")} className="rounded-xl bg-white/10 px-4 py-2.5 text-sm font-bold text-white ring-1 ring-white/20">CSV</button></div></div></section>
 <section className="grid gap-3 rounded-2xl border bg-white p-4 shadow-sm md:grid-cols-3 xl:grid-cols-7">{[["from","From"],["to","To"]].map(([k,l])=><label key={k} className="text-xs font-semibold text-slate-500">{l}<input type="date" value={filters[k]} onChange={e=>set(k,e.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2 text-sm text-slate-800"/></label>)}{[["programId","Program",lists.programs],["batchId","Batch",filteredB],["districtId","District",lists.districts],["blockId","Block",filteredBl],["centerId","Center",filteredC]].map(([k,l,arr])=><label key={k} className="text-xs font-semibold text-slate-500">{l}<select value={filters[k]} onChange={e=>{set(k,e.target.value);if(k==="districtId"){set("blockId","");set("centerId","")}if(k==="blockId")set("centerId","")}} className="mt-1 w-full rounded-xl border px-3 py-2 text-sm text-slate-800"><option value="">All accessible</option>{arr.map(x=><option key={x._id} value={x._id}>{x.name||x.programName||x.batchName||x.districtName||x.blockName||x.centerName}</option>)}</select></label>)}<button onClick={load} className="rounded-xl bg-indigo-600 px-4 py-2 text-sm font-bold text-white">{loading?"Loading...":"Apply Filters"}</button></section>
 {error&&<div className="rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}{d&&<><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-8"><Card title="Active Students" value={d.summary.activeStudents}/><Card title="Present" value={d.summary.present}/><Card title="Absent" value={d.summary.absent}/><Card title="Attendance Rate" value={`${d.summary.attendanceRate}%`}/><Card title="Exams" value={d.summary.exams}/><Card title="Marks Uploaded" value={d.summary.marksUploaded}/><Card title="Absentee Calls" value={d.summary.callingLogs}/><Card title="PDF Uploads" value={d.summary.pdfUploads}/></section>
 <div className="grid gap-6 xl:grid-cols-2"><section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-bold text-slate-900">Attendance Trend</h2><div className="mt-4 space-y-2">{d.attendanceTrend.slice(-14).map(r=><div key={r.date} className="grid grid-cols-[90px_1fr_70px] items-center gap-3 text-xs"><span className="text-slate-500">{r.date}</span><div className="h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-indigo-500" style={{width:`${r.attendanceRate}%`}}/></div><span className="text-right font-bold">{r.attendanceRate}%</span></div>)}</div></section><section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-bold text-slate-900">Exam & Marks Completion</h2><div className="mt-4 space-y-3">{d.marksSummary.map(r=><div key={r.examId} className="rounded-xl bg-slate-50 p-3"><div className="flex justify-between"><b className="text-sm">{r.examName||r.subject}</b><span className="text-xs font-bold text-indigo-600">{r.completionRate}%</span></div><p className="mt-1 text-xs text-slate-500">{r.uploaded} / {r.expected} marks uploaded · Avg {r.average}</p></div>)}</div></section></div>
 <div className="grid gap-6 xl:grid-cols-3"><section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-bold">Top Performers</h2>{d.topPerformers.map((r,i)=><div key={r.studentId} className="flex justify-between border-b py-3 text-sm"><span><b>#{i+1} {r.name}</b><small className="ml-2 text-slate-400">{r.studentSrn}</small></span><strong>{r.average}</strong></div>)}</section><section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-bold">Students Needing Attention</h2>{d.lowPerformers.map((r,i)=><div key={r.studentId} className="flex justify-between border-b py-3 text-sm"><span><b>{i+1}. {r.name}</b><small className="ml-2 text-slate-400">{r.studentSrn}</small></span><strong className="text-rose-600">{r.average}</strong></div>)}</section><section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-bold">Absentee Calling</h2><p className="mt-2 text-3xl font-black text-indigo-700">{d.callingSummary.totalCalls}</p>{Object.entries(d.callingSummary.byType).map(([k,v])=><div key={k} className="mt-2 flex justify-between text-sm"><span>{k}</span><b>{v}</b></div>)}</section></div></>}</div></div>}
