import { useEffect, useState } from "react";
import { getCenterAttendanceUploadDashboard, exportCenterAttendanceUploadDashboard } from "../services/dashboard.service";
import { DashboardHeader, DashboardTable, DateRangeFilters, ErrorBox, ExportButton, LoadingBox, ProgramBatchFilters, RegionFilters, monthStart, today, useDashboardOptions } from "../components/dashboardCommon";

export default function CenterAttendanceUploadDashboard() {
  const { options } = useDashboardOptions();
  const [filters, setFilters] = useState({ programId: "", batchId: "", districtId: "", blockId: "", centerId: "", from: today(), to: today(), notUploaded: false });
  const [data, setData] = useState(null); const [loading, setLoading] = useState(false); const [exporting, setExporting] = useState(false); const [error, setError] = useState("");
  const load = async () => { if ((options.programs.length > 1 || options.batches.length > 1) && (!filters.programId || !filters.batchId)) { setError("Select Program and Batch because multiple program/batch assignments are available."); return; } try { setLoading(true); setError(""); setData((await getCenterAttendanceUploadDashboard(filters)).data); } catch (e) { setError(e.response?.data?.message || "Unable to load center upload dashboard"); } finally { setLoading(false); } };
  useEffect(() => { if (options.programs.length === 1 && options.batches.length === 1) setFilters((x) => ({ ...x, programId: String(options.programs[0]._id), batchId: String(options.batches[0]._id) })); }, [options.programs, options.batches]);
  const exportExcel = async () => { try { setExporting(true); await exportCenterAttendanceUploadDashboard(filters); } catch (e) { setError(e.response?.data?.message || "Unable to export upload status"); } finally { setExporting(false); } };
  return <div className="min-h-full space-y-6 p-4 sm:p-6 lg:p-8">
    <DashboardHeader eyebrow="Dashboards / Center Attendance Upload" title="Center-wise Attendance Upload"><ExportButton permission="dashboard.center-attendance-upload.export" onClick={exportExcel} loading={exporting}>Export Excel</ExportButton></DashboardHeader>
    <ProgramBatchFilters filters={filters} setFilters={setFilters} options={options} mandatory={options.programs.length > 1} showDate onApply={load} />
    <RegionFilters filters={filters} setFilters={setFilters} options={options} onApply={load} notMarkedLabel="Not Uploaded" />
    <ErrorBox message={error} />
    {loading ? <LoadingBox text="Loading center upload status..." /> : data ? <><section className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border bg-white p-5"><p className="text-xs font-black uppercase text-slate-400">Total</p><p className="mt-2 text-3xl font-black">{data.summary.total}</p></div><div className="rounded-2xl border border-emerald-100 bg-emerald-50 p-5"><p className="text-xs font-black uppercase text-emerald-700">Total Uploaded</p><p className="mt-2 text-3xl font-black text-emerald-800">{data.summary.uploaded}</p></div><div className="rounded-2xl border border-amber-100 bg-amber-50 p-5"><p className="text-xs font-black uppercase text-amber-700">Pending</p><p className="mt-2 text-3xl font-black text-amber-800">{data.summary.pending}</p></div></section><DashboardTable title="District / Block / Center Upload Status" rows={data.table} columns={[{ key: "district", label: "District" }, { key: "block", label: "Block" }, { key: "center", label: "Center" }, { key: "batch", label: "Batch" }, { key: "uploaded", label: "Upload Status", render: (r) => r.status === "Uploaded" ? <span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-700">1</span> : <span className="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-bold text-amber-700">0</span> }]} /><DashboardTable title="Center Coverage" rows={data.byCenter || []} columns={[{ key: "district", label: "District" }, { key: "block", label: "Block" }, { key: "center", label: "Center" }, { key: "uploads", label: "Uploads" }, { key: "latestUpload", label: "Latest Upload", render: (r) => r.latestUpload ? new Date(r.latestUpload).toLocaleDateString() : "-" }]} compact />
      <DashboardTable title="Upload History" rows={data.history || []} columns={[{ key: "date", label: "Date", render: (r) => r.date ? new Date(r.date).toLocaleDateString() : "-" }, { key: "district", label: "District" }, { key: "block", label: "Block" }, { key: "center", label: "Center" }, { key: "batch", label: "Batch" }, { key: "centerCode", label: "Center Code" }, { key: "fileName", label: "File" }]} /></> : null}
  </div>;
}
