import { useEffect, useMemo, useState } from "react";
import { getExamsMarksDashboard, getExamMarksReport, exportExamMarksReport, exportExamStudentsData } from "../services/dashboard.service";
import { DashboardHeader, DashboardTable, DateInput, ErrorBox, ExportButton, LoadingBox, ProgramBatchFilters, RegionFilters, today, useDashboardOptions } from "../components/dashboardCommon";

export default function ExamsMarksDashboard() {
  const { options } = useDashboardOptions();
  const [filters, setFilters] = useState({ programId: "", batchId: "", from: "", to: "", subject: "", examType: "" });
  const [data, setData] = useState(null); const [report, setReport] = useState(null); const [region, setRegion] = useState({ districtId: "", blockId: "", centerId: "" }); const [loading, setLoading] = useState(true); const [reportLoading, setReportLoading] = useState(false); const [exporting, setExporting] = useState(false); const [studentExporting, setStudentExporting] = useState(false); const [error, setError] = useState("");
  const load = async () => { try { setLoading(true); setError(""); setData((await getExamsMarksDashboard(filters)).data); } catch (e) { setError(e.response?.data?.message || "Unable to load exams dashboard"); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const openReport = async (examId) => { try { setReportLoading(true); setError(""); setReport((await getExamMarksReport({ examId, ...region })).data); } catch (e) { setError(e.response?.data?.message || "Unable to load exam report"); } finally { setReportLoading(false); } };
  const exportReport = async () => { if (!report?.exam?._id) return; try { setExporting(true); await exportExamMarksReport({ examId: report.exam._id, ...region }); } catch (e) { setError(e.response?.data?.message || "Unable to export exam report"); } finally { setExporting(false); } };
  const exportStudents = async () => { if (!report?.exam?._id) return; try { setStudentExporting(true); await exportExamStudentsData({ examId: report.exam._id, ...region }); } catch (e) { setError(e.response?.data?.message || "Unable to export exam students"); } finally { setStudentExporting(false); } };
  const subjects = useMemo(() => [...new Set((data?.filters?.exams || []).map((x) => x.subject).filter(Boolean))], [data]);
  return <div className="min-h-full space-y-6 p-4 sm:p-6 lg:p-8">
    <DashboardHeader eyebrow="Dashboards / Exams & Marks" title="Exams & Marks Upload"><span /></DashboardHeader>
    <ProgramBatchFilters filters={filters} setFilters={setFilters} options={options} showDate onApply={load} />
    <section className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-2"><label className="text-[11px] font-black uppercase tracking-wider text-slate-500">Subject<select value={filters.subject} onChange={(e) => setFilters((x) => ({ ...x, subject: e.target.value }))} className="mt-1.5 w-full rounded-xl border px-3 py-2.5 text-sm normal-case"><option value="">All subjects</option>{subjects.map((s) => <option key={s}>{s}</option>)}</select></label><label className="text-[11px] font-black uppercase tracking-wider text-slate-500">Exam Type<input value={filters.examType} onChange={(e) => setFilters((x) => ({ ...x, examType: e.target.value }))} placeholder="Exam type (if configured)" className="mt-1.5 w-full rounded-xl border px-3 py-2.5 text-sm normal-case" /></label></section>
    <ErrorBox message={error} />
    {loading ? <LoadingBox text="Loading exams and marks..." /> : <DashboardTable title="Exam Summary" rows={data?.rows || []} columns={[{ key: "examId", label: "Exam ID" }, { key: "examName", label: "Exam Name" }, { key: "subject", label: "Subject" }, { key: "examDate", label: "Exam Date", render: (r) => new Date(r.examDate).toLocaleDateString() }, { key: "totalEnrolled", label: "Total Enrolled Students" }, { key: "marksUpdated", label: "Total Marks Updated" }, { key: "pendingMarks", label: "Pending Marks" }, { key: "view", label: "Report", render: (r) => <button onClick={() => openReport(r.examId)} className="rounded-lg bg-indigo-600 px-3 py-1.5 text-xs font-bold text-white">View full report</button> }]} />}
    {reportLoading ? <LoadingBox text="Opening full report..." /> : report ? <section className="space-y-4 rounded-3xl border border-slate-200 bg-slate-50 p-4 sm:p-6"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-black uppercase tracking-wider text-indigo-600">Full report</p><h2 className="text-2xl font-black text-slate-900">{report.exam.examName}</h2><p className="text-sm text-slate-500">{report.exam.examCode} · {report.exam.subject}</p></div><div className="flex flex-wrap gap-2"><ExportButton permission="dashboard.exams-marks.export" onClick={exportReport} loading={exporting}>Export Report</ExportButton><ExportButton permission="dashboard.exams-marks.student-export" onClick={exportStudents} loading={studentExporting}>Export Students Data</ExportButton></div></div><RegionFilters filters={region} setFilters={setRegion} options={options} onApply={() => openReport(report.exam._id)} /><DashboardTable title="District / Block / Center Marks Report" rows={report.table} columns={[{ key: "district", label: "District" }, { key: "block", label: "Block" }, { key: "center", label: "Center" }, { key: "srn", label: "SRN" }, { key: "name", label: "Name" }, { key: "totalMarks", label: "Total Marks" }, { key: "obtainedMarks", label: "Obtained Marks" }, { key: "marksUploaded", label: "Marks Uploaded", render: (r) => r.marksUploaded ? "Yes" : "No" }]} /></section> : null}
  </div>;
}
